services:
  # flask:
  #   build: .
  #   volumes:
  #     - .:/app
  #     - ./workspace:/workspace
  #   ports:
  #     - 9000:5000

  mysql:
    image: mysql:9.0.1
    container_name: gaeun_mysql
    restart: always
    ports:
      - 9001:3306
    environment:
      MYSQL_ROOT_PASSWORD: gaeun
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  vscode:
    build:
      context: .
      dockerfile: Dockerfile.vscode
    container_name: gaeun_vscode
    volumes:
      - .:/app
      - ./workspace:/workspace
      - ./start.sh:/start.sh
    ports:
      - 9002:80
      - 9000:5000
